image: node:latest
stages:
  - publish

publish:
  stage: publish
  script:
    - echo "${CI_SERVER_HOST} ${CI_PROJECT_ID} ${CI_JOB_TOKEN}"
    - echo "https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "@contextualize:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - cat .npmrc
    - npm publish --verbose

pages:
  stage: publish
  script:
    - npm install
    - npm run storybook-build
  artifacts:
    paths:
      - public
